In [2]:
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9,])
print(array)
type(array)

[0 1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [3]:
import numpy as np
array = np.ones((3,3),dtype=bool)
print(array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.where(a%2 ==0)
print(b)

(array([1, 3, 5, 7, 9], dtype=int64),)


In [5]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = c%2 == 1
c[d] = -1
print (c)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [7]:
import numpy as np
e=np.array([1,2,3,4,5,6,7,8])
print(e)
f = e.reshape(2,4)
print(f)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [11]:
import numpy as np
g = np.arrange(1,10).reshape(3,3)
print(g)
h = np.arrange(10,19).reshape(3,3)
print(h)

AttributeError: module 'numpy' has no attribute 'arrange'

In [19]:
x = np.array([2,4,6,8,10])
y = np.array([3,5,7,9,11,13])
z = np.concatenate((x, y))
print(np.sum(np.concatenate((x[x>=10],y[y<=14]))))

58


In [18]:

import numpy as np
one = np.ones(3)
two = one + one
three = one * 3

repeat = np.arrange(1,4)
print(repeat)
tile = np.tile(repeat, 3)
print(tile)

AttributeError: module 'numpy' has no attribute 'arrange'

In [27]:
# Create 2 array, remove repeating numbers and combine
import numpy as np
x = np.array([1,2,3,4,5,6,7])
y = np.array([4,5,6,7,8,9])
x = np.concatenate((x, y))
print(x)
x = np.unique(x, axis = 0)
print(x)

a = np.arrange(1, 8)
b = np.arrange(4,10)
print(a)
print(b)

c = np.setdiff1d(b, a)

print(c)

[1 2 3 4 5 6 7 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


AttributeError: module 'numpy' has no attribute 'arrange'

In [28]:
# Sum values of 4 to 8 together
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
c = np.concatenate((a, b))
d = c >=3
print(d)
e = c[d]
print(c)
print(e)
f = e < 7
g = e[f]
print(g)
final = np.sum(g)
print(final)

[False False  True  True  True  True  True  True  True  True  True]
[1 2 3 4 5 4 5 6 7 8 9]
[3 4 5 4 5 6 7 8 9]
[3 4 5 4 5 6]
27


In [32]:
import numpy as np
a = np.array([2,4,6,8,10,12])
b = np.array([4,5,6,7,8,9,10,11])
c = np.concatenate((a, b))
print(d)
print(sum(d))

[False False  True  True  True  True  True  True  True  True  True]
9
